In [90]:
# importing essential modules
import numpy as np
import pandas as pd

In [91]:
# importing dataset
df = pd.read_csv("Titanic-Dataset.csv")

In [92]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [93]:
# get the count of duplicated rows
df.duplicated().sum()

np.int64(0)

In [94]:
# get the information of dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [95]:
# get the percentage of missing values in every single colmun
(df.isna().sum())*100/len(df)

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [96]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [97]:
# remove the 'PassengerId', 'Name' and Ticket columns
df = df.drop(columns=['PassengerId','Name', 'Ticket'])

In [98]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [99]:
# get the the unige values from 'Sex' column
df['Sex'].unique()

array(['male', 'female'], dtype=object)

In [100]:
# get the the unige values from 'Cabin' column
df["Cabin"].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64', 'E24', 'C90', 'C45', 'E8', 'B101', 'D45', 'C46', 'D30',
       'E121', 'D11', 'E77', 'F38', 'B3', 'D6', 'B82 B84', 'D17', 'A36',
       'B102', 'B69', 'E49', 'C47', 'D28', 'E17', 'A24', 'C50', 'B42',
       'C148'], dtype=object)

In [101]:
# get the the unige values from 'Embarked' column
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [102]:
# converting the categorical values to numerical values (0, 1)
binary_map = {'male' : 1, 'female' : 0}
df['Sex'] = df['Sex'].map(binary_map)

df

     Survived  Pclass  Sex   Age  SibSp  Parch     Fare Cabin Embarked
0           0       3    1  22.0      1      0   7.2500   NaN        S
1           1       1    0  38.0      1      0  71.2833   C85        C
2           1       3    0  26.0      0      0   7.9250   NaN        S
3           1       1    0  35.0      1      0  53.1000  C123        S
4           0       3    1  35.0      0      0   8.0500   NaN        S
..        ...     ...  ...   ...    ...    ...      ...   ...      ...
886         0       2    1  27.0      0      0  13.0000   NaN        S
887         1       1    0  19.0      0      0  30.0000   B42        S
888         0       3    0   NaN      1      2  23.4500   NaN        S
889         1       1    1  26.0      0      0  30.0000  C148        C
890         0       3    1  32.0      0      0   7.7500   NaN        Q

[891 rows x 9 columns]

In [103]:
# converted categorical variables into dummy variables
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
df = pd.get_dummies(df, columns=['Embarked'], dtype=int)
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked_C,Embarked_Q,Embarked_S
0,0,3,1,22.0,1,0,7.2500,NaN,0,0,1
1,1,1,0,38.0,1,0,71.2833,C85,1,0,0
2,1,3,0,26.0,0,0,7.9250,NaN,0,0,1
3,1,1,0,35.0,1,0,53.1000,C123,0,0,1
4,0,3,1,35.0,0,0,8.0500,NaN,0,0,1

In [104]:
# extract the cabin (first letter) from the Cabin column
df['Cabin'] = df['Cabin'].str[0]

# replace missing cabin values with 'Unknown'
df['Cabin'] = df['Cabin'].fillna('Unknown')

# converted categorical variables into dummy variables
df = pd.get_dummies(df, columns=['Cabin'], dtype=int)
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S,Cabin_A,Cabin_B,Cabin_C,Cabin_D,Cabin_E,Cabin_F,Cabin_G,Cabin_T,Cabin_Unknown
0,0,3,1,22.0,1,0,7.2500,0,0,1,0,0,0,0,0,0,0,0,1
1,1,1,0,38.0,1,0,71.2833,1,0,0,0,0,1,0,0,0,0,0,0
2,1,3,0,26.0,0,0,7.9250,0,0,1,0,0,0,0,0,0,0,0,1
3,1,1,0,35.0,1,0,53.1000,0,0,1,0,0,1,0,0,0,0,0,0
4,0,3,1,35.0,0,0,8.0500,0,0,1,0,0,0,0,0,0,0,0,1